name: 2Pink Update Schedule

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run script
        env:
          CRONJOB_API_KEY: ${{ secrets.CRONJOB_API_KEY }}
        run: python update_schedule.py
